[package]
name = "rkyv_derive"
version = "0.7.18"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Derive macro for rkyv"
license = "MIT"
documentation = "https://docs.rs/rkyv_derive"
repository = "https://github.com/rkyv/rkyv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"

[features]
default = []
arbitrary_enum_discriminant = []
archive_be = []
archive_le = []
copy = []
strict = []

[package.metadata.docs.rs]
all-features = true
