[package]
name = "rkyv_dyn"
version = "0.6.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Trait object support for rkyv"
license = "MIT"
documentation = "https://docs.rs/rkyv_dyn"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { version = "~0.5.1", optional = true }
inventory = "0.1"
lazy_static = "1.4"
ptr_meta = "~0.1.3"
rkyv = { version = "0.6", path = "../rkyv" }
rkyv_dyn_derive = { version = "=0.6.0", path = "../rkyv_dyn_derive" }
rkyv_typename = { version = "0.6", path = "../rkyv_typename" }

[features]
default = []
archive_le = ["rkyv/archive_le"]
archive_be = ["rkyv/archive_be"]
nightly = []
strict = ["rkyv/strict"]
validation = ["bytecheck", "rkyv/validation", "rkyv_dyn_derive/validation"]
vtable_cache = []

[package.metadata.docs.rs]
features = ["validation"]
