[package]
name = "backwards_compat"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = "~0.6.7"
rkyv = { version = "0.7", path = "../../rkyv", features = ["validation"] }
