name: Test Suite

concurrency: staging_environment

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-cross:
    name: Test (stable) - ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          # - aarch64-linux-android
          # - arm-linux-androideabi
          # - armv7-linux-androideabi
          # - i686-linux-android
          # - x86_64-linux-android
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - armv5te-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - mips-unknown-linux-gnu
          - mips64-unknown-linux-gnuabi64
          - mips64el-unknown-linux-gnuabi64
          - mipsel-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          # - x86_64-unknown-netbsd
          # - wasm32-unknown-emscripten
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - run: cargo install cross
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: cross build --target ${{ matrix.target }} --verbose
      - run: cross test --package rkyv_test --target ${{ matrix.target }} --verbose

  test-native:
    name: Test (stable) - ${{ matrix.display_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            display_name: Ubuntu 20.04
          - os: macos-10.15
            display_name: macOS 10.15
          - os: windows-2019
            display_name: Windows Server 2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose
      - run: cargo test --verbose
